-- TASK: A. Viết script tạo khóa chính, khóa ngoại và các ràng buộc cơ bản cho lược đồ CSDL ở trên.

DROP DATABASE IF EXISTS `QLGV`;
CREATE DATABASE `QLGV`;
USE `QLGV`;
CREATE TABLE `GIAOVIEN` (
    `MAGV` varchar(4) NOT NULL,
    `HOTEN` nvarchar(40),
    `LUONG` float,
    `PHAI` nvarchar(3),
    `NGSINH` date,
    `DIACHI` nvarchar(1000),
    `GVQLCM` varchar(4),
    `MABM` varchar(4),
    PRIMARY KEY (`MAGV`)
);
ALTER TABLE `GIAOVIEN` ADD CONSTRAINT `C_PHAI` CHECK (`PHAI` IN ('Nam', 'Nữ'));

CREATE TABLE `BOMON` (
    `MABM` varchar(4) NOT NULL,
    `TENBM` nvarchar(40),
    `MAKHOA` varchar(4),
    `PHONG` varchar(3),
    `DIENTHOAI` varchar(10),
    `TRUONGBM` varchar(4),
    `NGAYNHANCHUC` date,
    PRIMARY KEY (`MABM`)
);

CREATE TABLE `KHOA` (
    `MAKHOA` varchar(4) NOT NULL,
    `TENKHOA` nvarchar(40),
    `NAMTL` int,
    `PHONG` varchar(3),
    `DIENTHOAI` varchar(10),
    `TRUONGKHOA` varchar(4),
    `NGAYNHANCHUC` date,
    PRIMARY KEY (`MAKHOA`)
);

CREATE TABLE `DETAI` (
    `MADT` varchar(4) NOT NULL,
    `TENDT` nvarchar(40),
    `CAPQL` varchar(10),
    `KINHPHI` float,
    `NGAYBD` date,
    `NGAYKT` date,
    `MACD` varchar(5),
    `GVCNDT` varchar(4),
    PRIMARY KEY (`MADT`)
);

CREATE TABLE `CONGVIEC` (
    `MADT` varchar(4) NOT NULL,
    `SOTT` int NOT NULL,
    `TENCV` nvarchar(50),
    `NGAYBD` date,
    `NGAYKT` date,
    PRIMARY KEY (`MADT`, `SOTT`)
);

CREATE TABLE `THAMGIADT` (
    `MAGV` varchar(4) NOT NULL,
    `MADT` varchar(4) NOT NULL,
    `STT` int NOT NULL,
    `PHUCAP` float,
    `KETQUA` nvarchar(5),
    PRIMARY KEY (`MAGV`, `MADT`, `STT`)
);

CREATE TABLE `CHUDE` (
    `MACD` varchar(5) NOT NULL,
    `TENCD` nvarchar(40),
    PRIMARY KEY (`MACD`)
);

CREATE TABLE `GV_DT` (
    `MAGV` varchar(4) NOT NULL,
    `DIENTHOAI` varchar(10) NOT NULL,
    PRIMARY KEY (`MAGV`, `DIENTHOAI`)
);

CREATE TABLE `NGUOITHAN` (
    `MAGV` varchar(4) NOT NULL,
    `TEN` varchar(10) NOT NULL,
    `NGSINH` date,
    `PHAI` varchar(3),
    PRIMARY KEY (`MAGV`, `TEN`)	
);

ALTER TABLE GIAOVIEN ADD CONSTRAINT FK_GIAOVIEN_GIAOVIEN FOREIGN KEY (GVQLCM) REFERENCES GIAOVIEN(MAGV);
ALTER TABLE GIAOVIEN ADD CONSTRAINT FK_GIAOVIEN_BOMON FOREIGN KEY (MABM) REFERENCES BOMON(MABM);
ALTER TABLE KHOA ADD CONSTRAINT FK_KHOA_GIAOVIEN FOREIGN KEY (TRUONGKHOA) REFERENCES GIAOVIEN(MAGV);
ALTER TABLE BOMON ADD CONSTRAINT FK_BOMON_GIAOVIEN FOREIGN KEY (TRUONGBM) REFERENCES GIAOVIEN(MAGV);
ALTER TABLE DETAI ADD CONSTRAINT FK_DETAI_GIAOVIEN FOREIGN KEY (GVCNDT) REFERENCES GIAOVIEN(MAGV);
ALTER TABLE THAMGIADT ADD CONSTRAINT FK_THAMGIADT_GIAOVIEN FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV);
ALTER TABLE GV_DT ADD CONSTRAINT FK_GV_DT_GIAOVIEN FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV);
ALTER TABLE NGUOITHAN ADD CONSTRAINT FK_NGUOITHAN_GIAOVIEN FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV);
ALTER TABLE BOMON ADD CONSTRAINT FK_BOMON_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA);
ALTER TABLE THAMGIADT ADD CONSTRAINT FK_THAMGIADT_CONGVIEC FOREIGN KEY (MADT, STT) REFERENCES CONGVIEC(MADT, SOTT);
ALTER TABLE CONGVIEC ADD CONSTRAINT FK_CONGVIEC_DETAI  FOREIGN KEY (MADT) REFERENCES DETAI(MADT);
ALTER TABLE DETAI ADD CONSTRAINT FK_DETAI_CHUDE FOREIGN KEY (MACD) REFERENCES CHUDE(MACD);